### ISSUE TITLE
wrong URL's in cloned webpages

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#764] opened 2017-05-09 13:38 UTC
I cloned one Profil from Hub H1 with Hubzila Version 2.2 to Hub H2 with Version 2.3.2. The 'old' webpages from H1 are also cloned. But the in webpages contains images are on Hub H2 not displayed.

I see, that the image URL on Hub H2 is so:
_[baseurl-hub-h2]/[image-path-from-hub-h1]_. But this image isn't cloned and this image  exist not at Hub H2. I mean, that this URL at Hub H2 _[baseurl-hub-h2]/[image-path-from-hub-h1]_ is in this context wrong.

**Comment by zotlabs** [comment] 2017-05-17 00:39
duplicate of #769

Should be resolved for new content by commit ae89f1b3b3 which fixes the missing call to sync file contents.

**Closed** 2017-08-17 06:31 UTC
Labels: duplicate, retest please
