### ISSUE TITLE
Persistent Dutch text strings under Notices

### ISSUE THREAD

**Issue by mjfriaza** [redmatrix/hubzilla#71] opened 2015-10-06 04:59 UTC
In personal notifications tab, I get this message.:
"Manuel Jiménez Friaza, satipera gaf een reactie op een bericht van satipera hace 3 minutos"

Under images shared with Diaspora, you see this message:
"volledige grootte tonen"

It is as if they had mixed translations, Dutch and Spanish...
Jeroenprat, that is who upload my Spanish translation to the github, said:

"One thing I find is that all those strings you mentioned are in the Spanish strings.php and hstrings.php. So that is not the case. Another thing I find is that the Spanish strings.php (not hstrings.php) has more lines than the Dutch (2149 vs 2124). But that should actually reverse your problem.

So please submit an issue on Github. In the meantime I will change the hub default to English and see if I experience the same problem. You are allowed to copy and paste this message into the Github issue."

EDITED:
Jeroenprat changed the default language of your hub to English. Under images shared with Diaspora reappears "View full size", but nothing changes in Personal Notifications tab.

**Comment by jeroenpraat** [comment] 2015-10-06 11:50
I can reproduce this, so I can confirm this. When I change my language to Spanish, I still see Dutch hover text under Notices and Dutch on notifications/system; like this: "jeroenpraat, Mike Macgirvin gaf een reactie op een bericht van George Ellenburg hace 8 horas". When I change my language to German, I get the same behaviour: "jeroenpraat, Mike Macgirvin gaf een reactie op een bericht van George Ellenburg vor 8 Stunden". And I can go on like that. So it's not related to the Spanish language strings. I also changed the default language to English on my hub, but that doesn't change the above mentioned text.

To be sure, I cleared my browser cache, emptied store/[data]/smarty3/compiled/, restarted my browser and tested it in both the latest Firefox and Chromium.

**Comment by jeroenpraat** [comment] 2015-10-30 12:51
I think I've found it. Somehow the notify text is set to someone's account language, not their channel language. When I look into the database account language's are set to the default site language when the account is created. That's no issue when that account language is not used. Let me see why the notify text is using that.

**Comment by jeroenpraat** [comment] 2015-10-30 13:01
This is probably it, but I don't know how to change it. It's in enotify.php (line 55) (used for e-mail notifications?), but probably also used for the notifications on the hub. It is also a known issue so to see. 

````php
push_lang($recip['account_language']); // should probably have a channel language

**Comment by jeroenpraat** [comment] 2015-10-30 13:16
The problem is that the channel language is temporary stored in the session table. The only solution is I think that the localized bits are not stored in notify_msg, but generated when viewing the notifications. I'm afraid here stops my know-how (actually I'm quite proud on how far I came). A workaround is to let the users change their account_language.  I can change it in the database myself, but that's not a solution of course.

**Comment by jeroenpraat** [comment] 2015-10-30 13:22
And of course we have the problem that this in include/account.php:179
````php
dbesc(get_best_language()),
````
...doesn't find the user's web browser language when signing up, but uses the default site language (I presume that one is only used when detecting the user's web browser language failed).

**Comment by jeroenpraat** [comment] 2015-10-30 13:54
Accounts on Redmatrix.nl have their account_language set to their browser's language. The last account created on that hub is on August 28th and until then it worked as expected. 

But, when I compare relevant files like include/account.php and include/language.php they are almost the same. Except two (I think) unrelated commits. So I'm lost here.

**Comment by jeroenpraat** [comment] 2015-10-30 14:42
I did some tests. When I create a new account with the browser changed to Spanish the account_language is Spanish. So forget what I said about that get_best_language doesn't work. 

I now remember why Manuel's account_language was set to Dutch, because I created (as agreed) his account. So that explains that. 

The only two issues that remain are feature requests (option to change account_language and using channel language in msg_notify). I close this issue. Sorry for the confusion and (probably) email spam.

**Closed by jeroenpraat** 2015-10-30 14:42 UTC
Labels: bug
