### ISSUE TITLE
Bug Installation with http

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#190] opened 2015-11-26 19:14 UTC
Today I observe new installations can be done with not https 
https://blablanet.com/display/d066fd31d2f371f351368a25362d409f128676c90077360b644696734c9b3353@blablanet.com?

There also now in the queue many servers with http

**Comment by redmatrix** [comment] 2015-11-26 19:45
Duplicate of #172

**Closed** 2015-12-09 02:29 UTC
Labels: duplicate
