### ISSUE TITLE
Custom theme/schema not working

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#797] opened 2017-05-27 02:29 UTC
Before the big theme-revamp we had a redbasic-derived custom theme which (unsurprisingly) doesn't work anymore, so I'm trying to re-develop it. I can only find snippets of the old docu but I remember what I did last year. Now, whatever I do, it does not work. 
My first step is to clone redbasic, change the name and _init and activate it. Now I would expect to have 2 identical themes but that's not the case: The scrolling behaviour changes: In redbasic the left menu is sticky, only the right side content scrolls. In the cloned theme the left side doesn't stick but scrolls together with the right side. Also the color schemes get lost by copying.
So obviously, just by cloning, some theme-behaviour gets lost.
Secondly I'm trying to change the color of .bg-inverse in css/style.css of the cloned theme (like I did last year) but that has no effect. There are overrides I can't find. 
It seems that the possibility to use derived custom themes somehow got lost during the interface revamp (which I really like btw).
Also I can't get the remnants of old, now nonfunctional themes out of the database, although I've long deleted them. The log file runs full with hundreds of lines of warnings: "check_plugin_versions: maxversion limit: homesocial".

**Comment by git-marijus** [comment] 2017-05-27 18:20
> The scrolling behaviour changes: In redbasic the left menu is sticky, only the right side content scrolls. In the cloned theme the left side doesn't stick but scrolls together with the right side. Also the color schemes get lost by copying.

Make sure you pick up the changes in /view/theme/redbasic/js/redbasic.js

> Also the color schemes get lost by copying.

IIRC color schemes are not supported anymore for derived themes

> Secondly I'm trying to change the color of .bg-inverse in css/style.css of the cloned theme (like I did last year) but that has no effect. There are overrides I can't find.
> It seems that the possibility to use derived custom themes somehow got lost during the interface revamp 

Make sure you have min/max version set correctly. Otherwise we fallback to the default theme.

> Also I can't get the remnants of old, now nonfunctional themes out of the database, although I've long deleted them. The log file runs full with hundreds of lines of warnings: "check_plugin_versions: maxversion limit: homesocial".

You might still have the theme enabled somewhere (admin section maybe? or a channel on your hub?) 

Anyway, 2.4 will bring even more changes to redbasic. Especially many class changes for nav and buttons. If you plan to do some work for your theme i suggest to build this against 2.4RC or 2.4 which will be probably released in the next week.

Also, if your theme does not change any templates, i suggest you to go with a custom scheme instead of a derived theme. Schemes are quite powerful - you can override any css with them plus set or preset all custom theme settings. See: /view/themes/redbasic/schema

**Comment by ilu33** [comment] 2017-05-27 21:14
Thank you for your hints. Our hub is on dev branch - surely 2.4 shouldn't bring anything we don't already have? 
The problem with schemes is that I can't set them as admin for the whole hub. At the moment users start out with a header bar totally black on black - or dark grey on black.  Our logo and standard avatar happens to be mostly dark as well. So the top of the screen is a black mess. I want to change the default background color for everybody to something light.
As an aside: Hubzlla devs should re-think whether the standard redbasic theme and color scheme - dark-grey on black - is really suitable. It definitely doesn't suit anybody with bad eyesight. It would be much better if a color scheme like BS-Default became default.

**Comment by git-marijus** [comment] 2017-05-28 08:25
>The problem with schemes is that I can't set them as admin for the whole hub.

IIRC you just need to link default.css and default.php to yourscheme.css and yourscheme.php to set a scheme systemwide.

**Comment by ilu33** [comment] 2017-06-01 00:34
I linked 2 testfiles (I copied bluegrid.*) as default.php and default.css into view/theme/schema but it had no effect. The hubzilla default schema looked same as before. I copied the files there, still no effect.
The code block in style.php in line 62 starts with 
```php
if (! $schema) {
```
I'm not sure I understand the condition correctly. To me it seems like style.php ignores this codeblock and sets the defaults from line 77 ff. instead? 

Just in case this matters: Advanced Theme and Layout Settings is turned off and locked because I want this to be configured by admin only.

**Comment by ilu33** [comment] 2017-06-03 13:54
I did some more tests. As soon as I log out, the custom schema gets applied to the login screen (easy to see since I test with bluegrid). Bluegrid also appears on help and pong but not on user pages like channels. I thought this might be a database issue again although I can't imagine how postgresql might be involved this time ... and on this hub nobody ever used custom colours. I've looked through the config table but nothing there looks suspicious. Any hints how I can debug this further?

Btw bluegrid menu colors seems to be broken (white on white), I will check that as soon as the underlying mechanism gets fixed.

Also the logo you can add via the addmin interface seems to always get resized to 56px × 19px which is much too small for the new layout. Is that hardcoded somewhere?

**Comment by ilu33** [comment] 2017-06-05 17:44
Looks good so far. I'll test some more.

**Comment by git-marijus** [comment] 2017-06-06 11:20
> For a short moment I thought you fixed the logo issue too but now it's back to its original microsize.

This is not a bug. We limit the height of the banner image to 1.35rem so that the banner can not expand the navbar. That is by design.
You can override that. The relevant css is this:
```
#banner img {
	max-height: 1.35rem;
	width: auto;
}
```

Anyway, i consider the scheme/theme issue closed. If you think the image in the banner should be handled different please open a new issue for that.

**Closed by git-marijus** 2017-06-06 11:20 UTC
Labels: bug, retest please
