### ISSUE TITLE
email_notify icon hz-white-xx.png shows up in two places on toolbar, confusing users

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/hubzilla#156] opened 2015-11-14 04:10 UTC
[![imagebin](http://upimage.mamalibre.com.ar/up/516b3e4ea396205187975f0088189113.png)](http://upimage.mamalibre.com.ar/#516b3e4ea396205187975f0088189113.png)

2 logos fix

The email_notify() icon hz-white-xx.png displays in two places on the tool bar, confusing some users.

**Comment by redmatrix** [comment] 2015-11-16 05:10
I can't access the imagebin URL (times out). Is this supposed to be an issue report or a patch? If it's an issue report, could you please describe the issue in a way that describes the expected behaviour and the actual behaviour, and if it's a patch please submit a pull request.

**Comment by royalterra** [comment] 2015-11-17 21:17
That domain hubzilla.ml is down coming the access url of a domain provider

**Comment by mama21mama** [comment] 2015-11-18 01:00
change your DNS
hubzilla.ml > hubzilla.mamalibre.com.ar

**Comment by kenrestivo** [comment] 2015-11-19 02:53
The source of this appears to be here:
https://github.com/redmatrix/hubzilla/blob/master/include/network.php#L1599

And/or here:

https://github.com/redmatrix/hubzilla/blob/master/include/enotify.php#L443

Marking as UX not bug because this might be the intended behavior, but it is obviously confusing to some users.

**Comment by redmatrix** [comment] 2015-11-19 09:14
In both those references, the logo image is being used inside an email body. This is unrelated to the nav template. The one in the center is coming from the site banner (configurable in the admin site panel) and I don't know at this moment whether it is the default banner. The one next to the search bar is unknown to me - I've never seen it. It's possibly another variant/instance of the banner text that hasn't been positioned correctly.

**Comment by redmatrix** [comment] 2015-11-19 23:31
The default banner content for a site (what is displayed by default in the center of the top navigation bar) is either the sitename or the text 'red' (I just fixed this so in the future it will always be the sitename).

There is no place in the code where this particular image is used in the navigation (top) region of the page. If you use the bluegrid scheme the image will appear as background for the notification popups in the top-right of the content area (just below the navigation region). You may also see this image in email notifications. These email notifications are never displayed on the website. 

This means that there is a very high probability the banner text for this site has been set/altered by the administrator to specifically add this logo image. The only other possibility is that you are using some other theme than the project default (redbasic); in which case you should probably contact the theme maintainer for that theme.

If you desire this image in a custom banner, please visit admin/site as the site administrator and remove the content from the custom banner. This issue should be resolved. If you desire to use this logo in a custom website banner, please try again.

**Comment by kenrestivo** [comment] 2015-11-19 23:33
So this is a problem with their template?

**Comment by redmatrix** [comment] 2015-11-19 23:40
Most likely a problem with custom site config settings. (specifically the config system.banner). It could be a template issue if it's a non-standard theme; but it looks to me like it's redbasic with default theme settings. Visiting the site (either anonymously or via remote-auth) I only see the center image and not the one on the right, so it's possible this has already been resolved.

**Comment by redmatrix** [comment] 2015-12-16 04:26
No reply and a dubious bug. I'm closing, please re-open if it is still a problem and you are willing to work with us to discover the source of the issue. I do not believe it is a code problem but instead is likely to be a site configuration problem.

**Closed by redmatrix** 2015-12-16 04:26 UTC
Labels: UX
