### ISSUE TITLE
Markdown conversion: problem with quotes on Friendica

### ISSUE THREAD

**Issue by AlfredSK** [redmatrix/hubzilla#793] opened 2017-05-22 13:45 UTC
Hello,
I've encountered an issue with quotes in posts. In Hubzilla everything looks okay. But the transport via Diaspora protocol puts the end of the quote at the wrong place.

**Link to discussion:**
https://helpers.pyxis.uberspace.de/display/0b6b25a82159206c21434ef413891924

**What I wrote:**
```
[.....]
as @mike@macgirvin.com pointed out in a [url=https://github.com/redmatrix/hubzilla/issues/779#issuecomment-301944037]Github issue[/url] there is an experimental database structure for utf8mb4.
[quote]the newer experimental database structure which is utf8mb4[/quote]
Is there a script for changing the database structure to use utf8mb4 collation? Is it necessary/recommended to switch to RC/dev branch for this purpose?

Thank you.
```

**How does it look in Friendica (source code of message):**

`<div class="wall-item-body e-content p-name" id="wall-item-body-2696978">Hello @<a href="https://gravizot.de/channel/support" class="userinfo mention" title="Hubzilla Support Forum+">Hubzilla Support Forum+</a><br>as @mike@macgirvin.com pointed out in a <a href="https://github.com/redmatrix/hubzilla/issues/779#issuecomment-301944037" target="_blank">Github issue</a> there is an experimental database structure for utf8mb4.<blockquote>the newer experimental database structure which is utf8mb4<br>Is there a script for changing the database structure to use utf8mb4 collation? Is it necessary/recommended to switch to RC/dev branch for this purpose?</blockquote>Thank you.<div class="body-attach"><div class="clear"></div></div></div>`

As you can see the closing tag of the blockquote is at the wrong place.

**Why?** @Hypolite discovered this:

> The formatting problem is related to Markdown, the > character opens a quote until the next double line feed, however in the raw message, the double line feed only comes after the question, see:
```
as @mike@macgirvin.com pointed out in a [Github issue](https://github.com/redmatrix/hubzilla/issues/779#issuecomment-301944037 '') there is an experimental database structure for utf8mb4.  
> the newer experimental database structure which is utf8mb4  
Is there a script for changing the database structure to use utf8mb4 collation? Is it necessary/recommended to switch to RC/dev branch for this purpose?  

Thank you.
```

And indeed, if I edit the post to add a newline after `[/quote]` everything looks good in Friendica. Same should be true for Diaspora. This issue seems to be related to markdown conversion.

Regards,
Steffen

**Comment by zotlabs** [comment] 2017-05-22 20:30
The issue is inside the html-to-markdown library Hubzilla is using (pixel418/markdownify) and needs to be fixed upstream. It is generally a stable and solid implementation but it's not a very active project so I've also been looking into alternative libraries. I've found one that appears to be better maintained and doesn't have this bug - and asked one of the Hubzilla developers to have a look at integrating it. 

The issue should be raised with the pixel418/markdownify project and perhaps a patch provided regardless. I've had a look but it's not going to be an easy sucker to track through the library code. They do appear to set a flag to indicate that two linebreaks should be added after blockquote elements - so the real question is why the end result has only one or why the double linebreak is perhaps in the wrong place.

**Comment by AlfredSK** [comment] 2017-05-22 20:49
Ah! Okay. An alternative markdown generator was suggested in the discussion.
>May I suggest using The PHP League's HTML to Markdown project we're currently using in Friendica instead?

https://github.com/thephpleague/html-to-markdown

**Comment by zotlabs** [comment] 2017-05-22 21:03
That's the one I recommended after looking at several candidates.

**Comment by zotlabs** [comment] 2017-05-23 23:55
This should be fixed in dev now. It's a bit late and potentially destabilising to get this into 2.4 , so we'll probably have to wait for the next release train to come through.

**Comment by AlfredSK** [comment] 2017-05-25 21:22
Great. Couldn't test yet because I stumbled about an issue with friend requests over diaspora protocol (friendica and diaspora). The probing of the profiles (handles and URLs) fails with current 'RC' and current 'dev'. :(

**Comment by zotlabs** [comment] 2017-05-26 00:31
[shrug] Works just fine for me probing both directions on current dev. 

Use the handle.

In case you setup a dedicated server to test, ensure the diaspora addon is enabled, the server is running 'standard' as opposed to 'pro', and the diaspora protocol is enabled in the Feature/Addon settings for the channel in question. 

If all of these check out, please provide the text of any error messages and/or specific steps to reproduce.

**Closed** 2017-08-17 06:30 UTC
Labels: retest please
