### ISSUE TITLE
Don't translate the "like" text

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla#148] opened 2015-11-11 15:41 UTC
If one watches a Hubzilla post from outside then it confuses very much that the likes are all translated in different languages:
- A likes B's status
- C gefällt B Status
- D gosta de status de B
- E vindt bericht van B leuk
- A Wave piace il messaggio di stato di B
- a F le gusta comment de B
- G liker B sin comment
  ...

This is totally confusing. It would be better if these texts wouldn't be translated in any language but would be in English at any time. The chance will be higher that it is understandable.

Alternatively the text could be translated in the preferred language of the thread starter.

**Comment by kenrestivo** [comment] 2015-11-19 19:49
Is this a duplicate of, or related to, https://github.com/redmatrix/hubzilla/issues/147 ?

**Comment by annando** [comment] 2015-11-19 21:04
@kenrestivo no.

**Comment by zotlabs** [comment] 2017-11-13 04:39
Unsigned like activities are no longer transmitted to Diaspora and Friendica, so this text should no longer be seen in those networks (as a consequence this information is now lost/discarded in those networks due to the closed design of the Diaspora protocol). In addition, the activities are created in the original author's language. Hubzilla could translate these activities into one language, but we don't do that because the original message content signatures would not validate.

**Closed by zotlabs** 2017-11-13 04:39 UTC
Labels: UX
