### ISSUE TITLE
posts from diaspora not coming

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#586] opened 2016-11-16 04:43 UTC
I do not know if it's already a known issue at the moment, maybe yes, but I have noticed that the federation with diaspora is not working  in the dev version .. I've done some tests in these hours in 2 different hubs using 'dev' and I  noticed that the channels no longer receive  posts that start from diaspora. Based on what I could understand the problem should be started 10 or 15 days ago,  but perhaps, repeating, you are already aware of this problem. 

Or am I just unlucky and I found 2 hubs with problems (if instead with you all works well).

ps: the only diaspora posts that appear are those mirrored by the clones (clones using master or redmatrix).

**Comment by zotlabs** [comment] 2016-11-16 04:46
Do you have the statistics_json addon enabled?

**Comment by elvecio** [comment] 2016-11-16 16:59
Yes, statistics_json addon enabled. I know one of the 2 admins,  I tell him to update, and see if it works.
Fed works with you?

**Comment by zotlabs** [comment] 2016-11-16 19:41
I don't use it personally. But one of my dev test sites receives some tagged public content and has received tagged content in the last week.

**Comment by ilu33** [comment] 2016-11-16 21:58
For us diaspora federation stopped working on either Nov 10th or 11th. 
Worked fine on Nov 9th without statistics_json addon. I thought you needed that only for tags working but not for connections? 
Anyway my diaspora connection still worked on our dev hub on Nov 9 but not on Nov 12th. On my account on Michaels hub, which is on the release channel, the diaspora connection still works.

**Comment by zotlabs** [comment] 2016-11-16 22:30
See issue #566 for reference. The statistics_json addon is now required for Diaspora to work. It is really only needed to use the tag relays and not for basic communication. Mario put a dependency to require it for the entire protocol plugin. Since then I changed some code so that one can still use the protocol plugin without statistics_json but you lose the ability to follow tags. I wasn't aware at the time of what Mario had changed, so the requirement to have statistics_json enabled first is still there. Your choices are to enable statistics_json, or remove statistics_json from the 'Requires:' line. If you do the latter you are welcome to check it in. Once you have done either of these actions re-enable the Diaspora plugin, since it will have been disabled.

**Comment by ilu33** [comment] 2016-11-16 22:58
Thank you, the diaspora plugin was indeed deactivated due to statistics_json. It will probably take a while until everything is fetched. I've read #566 but obviously my conclusions were completely wrong. 

This change has to be communicated, when the dev branch gets merged into master.

**Comment by zotlabs** [comment] 2016-11-17 02:01
Posts and comments appear to be working fine going both directions with current dev. I've removed the requirement to have statistics_json enabled, although without it you will not be able to follow tags or use public relays. If @elvecio is still having issues it is most likely due to being disabled. Git pull and re-enable.

**Comment by elvecio** [comment] 2016-11-18 02:12
Still having issues :-( (commit 0b0e0f8).... We need to re-enable statistics_json ( in this moment we have already "statistics_json" "diaspora") ?

**Comment by elvecio** [comment] 2016-11-19 00:50
we did 'git pull' , we re-enabled addons (statistic_json and also diaspora) and...nothing. Doesn't work here :-(.

**Comment by zotlabs** [comment] 2016-11-19 06:03
So apparently there aren't any fundamental issues/bugs because the configuration you describe is working well for others and I've also tested it and verified the functionality you claim is not working. So unless you want me to just tag this with 'WORKSFORME' and close the bug as a waste of time I'd recommend some further effort to describe the issue you are seeing and describe how others can reproduce it "exactly" because we are currently unable to reproduce it. This exercise will likely involve your system logfiles.  The following questions need to be answered -

- Does a Diaspora post with one of your site members as a recipient ever reach your site?
- If it reaches your site but does not get delivered to the recipient, was an error condition triggered which prevented delivery?
- If one sends a post from hubzilla which should be delivered to a Diaspora connection, has anybody looked at the delivery reports? What do they say? 
- And again for this condition what is logged for the delivery in the system logfile? Is the intended recipient listed in the log of recipients that will be delivered? Is their hub listed in the list of hubs that will be delivered to? What about the actual delivery process to that particular Diaspora server? What is reported about the delivery attempt? Did it succeed or did it fail? 

These events and especially any failures should all be logged.  Occasionally the actual problem may not be clearly evident, in which case it may be necessary to increase the loglevel to include more detail; and compare this with the Diaspora delivery code (addon/diaspora/inbound.php) to determine where the failure occurred. 

In the event where it appears that nothing at all is logged it may be necessary to examine the PHP logs (instructions for enabling these are at the bottom of your .htconfig.php file) to determine if there was a PHP error which aborted the process without logging anything. 
 
We cannot find this problem without your help. I've tried. Good luck.

**Comment by elvecio** [comment] 2016-11-19 13:09
the administrator  started yesterday to analyze the logs, apparently did not find anything. But this you have to argue with him.

In general, up to 15-20 days ago everything worked fine, then the messages coming from the diaspora are no longer arrived here, our messages  rather reach well diaspora.

I think the problems started after code changes followed to this problem https://github.com/redmatrix/hubzilla/issues/566 , But obviously I can not do much, since I am not the admin, and even the developer who can analyze the code changed in recent weeks. 
Coincidence or not, it all started with those changes.

**Comment by ilu33** [comment] 2016-11-21 07:24
You are right about the point it started but i can asure you it worked again after reenabling the addons. Just to be sure, check again in your account whether diaspora is activated there - it should be and it was for me, but checking can't harm. 
Your admin might check the loglevel which is set in .htconfig.php if I remember right. It should be set to "debug" or higher. Our main log showed quite clearly that the diaspora connection was not working.

@zotlabs  "If one sends a post from hubzilla which should be delivered to a Diaspora connection, has anybody looked at the delivery reports? What do they say? "
This was indeed weird because the delivery report of an undelivered mail says: "duplicate mail received 	2016-11-13 19:42:01". You usually wouldn't interprete this as "connection not working".

**Comment by elvecio** [comment] 2016-11-21 14:35
The posts from hubzilla reach without problem diaspora, while, as mentioned above, the posts that come from diaspora no longer reach hubzilla. check the settings is one of the first things, and mine are not changed, everything is enabled. In addition to being a 'veteran' of hubzilla, even my channels are 'veterans', and have always received posts from diaspora, but as of such changes in the code everything changed. In any case I can not do anything, it is now in the hands of the administrator who has to find the time to analyze all things...and the time is precious and everyone manages it as he wishes, fortunately or unfortunately....

**Comment by elvecio** [comment] 2016-11-22 01:04
We updated all the addons, and enabled again , and now it works. 
#fixed 
I'll close here. thanks. ;-)

**Closed** 2016-11-22 01:09 UTC
