### ISSUE TITLE
Installation fails under MySQL 5.7

### ISSUE THREAD

**Issue by MrSkigh** [redmatrix/hubzilla#407] opened 2016-06-07 15:17 UTC
I tried to install Hubzilla on a machine running with Ubuntu 16.04, PHP 7 and MySQL 5.7. The installation script crashed after the final step (the one with inserting the timezone etc.).

The Apache error log shows the following:
child pid xxxx exit signal Segmentation fault (11), possible coredump in /etc/apache2

And the MySQL error log shows:
Aborted connection xx to db: 'hubzilla' user: 'root' host: 'localhost' (Got an error reading communication packets)

The installation script connects to the database and creates the table 'abconfig' but fails directly afterwards.
What I have done now is to use MariaDB instead of MySQL which works fine. A different setup on a RPi2 with Debian using an older version of MySQL (should be 5.5) works flawless as well, so the error seems to relate to MySQL 5.7.

**Comment by royalterra** [comment] 2016-06-21 07:06
That sound to me more a bad configuration of your MYSQL I have already install in UBUNTU 16 and I not have any issues. I am not a lover of UBuntu 16 because many of the start scripts and service scripts not work any more correctly in many software. Not a problem of Ubuntu but many developers have not upgrade to the new standards also use in the last versions of Debian . That make more jobs to do manually and configurations with simple software like OPenfire, Gogs, etc
Anyway if you like to be with last version of Ubuntu why you not try MariaDB . Use the repository front here https://downloads.mariadb.org/mariadb/repositories/#mirror=coreix  make sure you use the last versions Stable https://downloads.mariadb.org/mariadb/repositories/#mirror=coreix&distro=Ubuntu&distro_release=xenial--ubuntu_xenial&version=10.1
Install MAriadb configure MAX Connections variable in my.cnf depending of your server ram , webs etc make a estimated  In my case I have something like that in some servers 
max_connections         = 5100
connect_timeout         = 5
wait_timeout            = 600
max_allowed_packet      = 16M
thread_cache_size       = 128
sort_buffer_size        = 4M
bulk_insert_buffer_size = 16M
tmp_table_size          = 32M
max_heap_table_size     = 32M
That is for give you a idea normally start with a small number that is because I have more of 32 GB of ram for MYSQL in your case need to be according to your ram a example for 8 GB can be 700 connections
Install mysqltuner with apt-get install mysqltuner and Time to time check the health of your MYSQL and check the Logs
With Mariadb I can confirm works perfect in Ubuntu 16

**Comment by zotlabs** [comment] 2017-03-02 03:53
This appears to be related to the MySQL strict mode of 5.7.4 and later. This particular issue should have been fixed in September 2016 although a few strict mode bugs still manifested themselves until 2.0 was released in December 2016. I'm not aware of any current strict_mode issues.

**Closed by zotlabs** 2017-03-02 03:53 UTC
