### ISSUE TITLE
CSS in Hubzilla version 2.4

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#806] opened 2017-06-01 08:00 UTC
> fwiw i noticed the sidebar menu on the settings page of the demo hub seems to be missing some CSS and isn't showing as a proper list menu. 

s. Mike's commentar in [Project hubs updated to 2.4](https://grid.reticu.li/channel/andrewmanning/&f=&mid=6f8fa571418ec2361fc7ec4d5c9d1a430a9bb16f65ddd56606b43804a3cd1758@grid.reticu.li?f=&jsdisabled=0) -thread from 05-31-2017 at 23:12

> The active tab is now white. 

 s. Martin's commentar in the same thread at 23:19

**Comment by git-marijus** [comment] 2017-06-02 07:45
This is probably due to some custom code at the demo hub.

**Comment by HappyPony** [comment] 2017-06-05 06:05
@anaqreon can you please make the custom code changes undo?

**Comment by git-marijus** [comment] 2017-06-06 18:29
It actually looks fine in my browser. @zotlabs do you still have an issue?

**Comment by zotlabs** [comment] 2017-06-06 19:59
Unfortunately yes.

**Comment by git-marijus** [comment] 2017-06-07 10:04
Hm... I managed to reproduce (allthough i don't know how)... Probably there was an issue with smarty chaches in the restored snapshot...
Please retry again!

**Comment by zotlabs** [comment] 2017-06-07 20:24
Looks fine. I think we also got the white tab sorted so we can probably close this.

**Closed** 2017-06-07 20:35 UTC
Labels: retest please
