### ISSUE TITLE
tag bug?

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#629] opened 2016-12-26 23:33 UTC
I think that  i found a new bug. When i tagged my own post then that post disappeared from my 'home', from my page (home channel page)  , and just remains  in my grid.
Someone else?

**Comment by elvecio** [comment] 2016-12-29 19:38
Perhaps I  found the culprit (the obvious culprit?): "Suppress Duplicate Posts / Comments"

Under certain conditions, or rather combinations ( have a channel and have another channel using the original channel as a source channel and everything must be done within the same hub and the "Suppress Duplicate Posts / Comments" enabled in the **not** original channel),  **delete** the original **post** written in a channel (the **original channel**). I have not done more tests with "Suppress Duplicate Posts / Comments" ... verily, I use very little this, so I'm not able to say how much damage this "Suppress Duplicate Posts / Comments" can cause or not cause. 
What I can say is that in the moment this thing deletes the original post, then it is a bit as not respect the _laws of robotics_.
ps:  definitely is a combination a bit 'crazy' and hard to repeat, to be implemented by someone else... but if someone has the same problem, probably he fell in the same combination.

**Comment by zotlabs** [comment] 2016-12-29 20:26
That is interesting if that's indeed what is happening, however 'Suppress duplicates' does not actually remove any posts. None. All it does is refuse to post an exact duplicate of an existing post (returns without storing anything). We also check that the copy of the post which looks exactly the same belongs to the same channel as the channel which is posting the duplicate. I'm not saying there isn't a bug - especially with such a complex delivery scenario as you describe, but I honestly don't believe that 'suppress' duplicates' is involved in the issue - at least not in the way you describe.

**Comment by elvecio** [comment] 2016-12-29 21:06
in fact the post **still exists**, but you can find only in the "**grid**", while in the /channel/MisterX (the channel home page) you can not find it anymore, it seems completely eliminated (hidden?) on that page.

**Comment by zotlabs** [comment] 2016-12-29 22:33
Then somewhere in the complex source delivery chain, community tag, or clone delivery (or a race condition involving all of these factors), item_wall was changed from 1 to 0.  

It is probably triggered by a clone delivery which wasn't received before the corresponding delivery chain was received. The clone delivery contains item_wall = 1. The regular delivery does not. So a clone could lose the item_wall flag if the site was really busy and the clone delivery was delayed. (Normally clones are delivered first).  Without a way to reproduce this reliably, the complex delivery chains involved make it much too difficult to track down.

If you just want to fix it set item_wall = 1 on that copy of the post.

**Comment by elvecio** [comment] 2016-12-29 23:49
I just discovered that this problem is just for public posts, I do not lose anything on my wall when I make a private post.

**Comment by elvecio** [comment] 2016-12-30 15:01
I finally think I've solved the puzzle, the problem actually seems to be the combination: normal/original channel, the clone channel, a channel using that channel as a source...
when I have **eliminated the channel that uses the source-channel** and just left original channel and his clone I have really **solved** the problem.
Maybe we need to do more tests to see if this problem is exactly this combination, having a channel that uses  the channel as source, in addition to the clone of course.

**Comment by elvecio** [comment] 2016-12-31 14:25
Update

you do not need the clone https://github.com/redmatrix/hubzilla/issues/635

**Closed** 2017-02-03 03:20 UTC
