### ISSUE TITLE
Delayed Posting

### ISSUE THREAD

**Issue by mjfriaza** [redmatrix/hubzilla#273] opened 2016-02-03 21:22 UTC
The 2/02 I postponed a publication to appear the Friday, 5, to the 8'38 of the morning and to expire the next day, Saturday, to the same hour.

However, as it can see  in this link, https://friendika.me4.it/display/bf8d6a631056b1f6726dd5f111595027 the post was published  immediately, at least, in friendica, possibly also in Diaspora, but I can not check him, because I do not have account in any pod. I can not contribute more information.

The date of publication in friendica updates  each 1 second. Really rare.

**Comment by redmatrix** [comment] 2016-02-04 00:11
I cannot duplicate. The ability to postpone publication requires your channel timezone to be correct or nearly correct, but generally this would only alter the publication within a 24 hour window based on how far off your timezone is. 

The syntax provided in the time selection field is somewhat strict. Generally you must use a string of the form yyyy-mm-dd hh:mm:ss ; there are exceptions but the exceptions are very specific to the 
English language. You could get away with 'next Friday' but not with 'próximo viernes'. If you provide a date/time that cannot be parsed and converted to UTC it will default to the current time and the post will not be delayed. 

Worth mentioning is that post expiration does not work on other networks. It is designed to work only within Hubzilla. Other networks will not remove the content at the selected time and it's possible they may not remove it ever.

**Comment by jeroenpraat** [comment] 2016-02-04 06:38
I as Manuel's admin can confirm that in the item database the parent mid is e6641ed185517ab129ba254fc2760e70520cc19fe350127ba35ccf7352d039f1@hubzilla.nl. The corresponding Friendica URL is https://friendika.me4.it/display/e6641ed185517ab129ba254fc2760e70520cc19fe350127ba35ccf7352d039f1@hubzilla.nl.

When I look into the item table for this mid + origin=1, I see Manuel's post with 2016-02-05 07:28:00 in the created and edited field. The expires field is set to 2016-02-06 07:29:00.

When I check the copies of that mid for other channels in the item table I notice that the created and edited fields are set oddly set to 2016-02-02 07:34:02. The expires fields are set to 2016-02-06 07:29:00 (as the origin).

So it looks like it went not only wrong  for Friendica/Diaspora accounts, but for his Hubzilla connections (at least on hubzilla.nl) as well.

**Comment by jeroenpraat** [comment] 2016-02-04 06:48
I can also confirm that the above post is indeed in the grid since yesterday of connected channels. Some Hubzilla members did even comment.

**Comment by redmatrix** [comment] 2016-02-05 00:54
> When I look into the item table for this mid + origin=1, I see Manuel's post with 2016-02-05 07:28:00 in 
> the created and edited field. The expires field is set to 2016-02-06 07:29:00.

I'm guessing that item_delayed = 0. The question is why this is the case. If we store a post that is more than ten minutes into the future we set item_delayed = 1 and refuse to deliver it to anything but clones. Those clones should preserve the created and edited dates - as well as the item_delayed flag. 

I'm not saying there isn't a bug. I'm saying I cannot figure out what kind of obscure error condition could result in this situation. The logic for delayed posts is very simple. There are four lines of code which determine a future post (include/items.php:L2303-2306). I cannot find a fault with them. If you can reproduce this, please let me know how. The only edge case I can come up with is that perhaps your system performed an NTP sync **in between** the two system calls and the system clock was immediately adjusted more than ten minutes; which resulted in the item_delayed flag not getting set to 1. If you can come up with a better explanation, I'm open to suggestions.

**Comment by jeroenpraat** [comment] 2016-02-05 01:29
The item_delayed =1 for the post with item_origin = 1 and item_created = 2016-02-05 07:28:00. The other items with the same mid (the copies) have item_delayed = 0 and item_created = 2016-02-02 07:34:02.

**Comment by mjfriaza** [comment] 2016-03-29 16:46
Yesterday I postponed a post 30 minutes and all was working properly. The issue is solved?

**Comment by jeroenpraat** [comment] 2016-03-29 17:46
Nothing is deliberately fixed AFAIK, but it can be possible that it was a temporary recession when you encountered this bug. I close this bug.

**Closed by jeroenpraat** 2016-03-29 17:46 UTC
