### ISSUE TITLE
Link funktioniert nicht

### ISSUE THREAD

**Issue by hfroese** [redmatrix/hubzilla#929] opened 2017-12-15 07:21 UTC
Nach dem Anklicken erscheint "Seite nicht gefunden"

![20171415-0818](https://user-images.githubusercontent.com/1968490/34031247-bbd22566-e170-11e7-81ca-a1bc6ea4789d.jpg)

**Comment by git-marijus** [comment] 2017-12-15 07:57
I guess you are talking about the "beitrag" link. Where does it link to?
In any case it seems we could not fetch the original post for a reason...

**Comment by hfroese** [comment] 2017-12-15 08:33
The link "Beitrag" points to
https://framasphere.org/posts/399575e0c395013538792a0000053625?zid=holger%40ioh.hfrc.de 
a reshare of one of my articles by a diaspora user.

**Comment by hfroese** [comment] 2017-12-15 09:42
Links like http://quitter.se/notice/21336481?zid=holger%40ioh.hfrc.de 
results in a public page only - not the linked article. It's because quitter in this case cannot handle "?zid=holger%40ioh.hfrc.de" ?

**Comment by git-marijus** [comment] 2017-12-15 11:27
The first part is probably fixed in https://github.com/redmatrix/hubzilla-addons/commit/828e3fd9ed6abb3f1001ad97c5fc22cc4e77c538

**Comment by hfroese** [comment] 2017-12-15 15:54
First part isn't fixed yet. Same problems after updating.

**Comment by git-marijus** [comment] 2017-12-16 09:26
@hfroese reported that the first issue is fixed. The update did not apply at first.

I investigated the quitter issue and it appears that the zid argument is indeed messing up things on the quitter site. That is probably an quitter issue. I wonder though if we can work around by not zidify the links to quitter...

**Comment by git-marijus** [comment] 2017-12-16 10:19
@zotlabs what about filtering by item['app']? Zidify plinks if there is no app only...

**Comment by hfroese** [comment] 2017-12-16 10:36
Please change "**schrieb**" to the correct term "**teilte**" also -  in languages files?

**Comment by git-marijus** [comment] 2017-12-16 10:44
@hfroese since the sentence refers to the original posters post 'wrote' (german 'schrieb') is the correct expression. E.G. [Profile image] Holger wrote the following post about an hour ago

**Comment by zotlabs** [comment] 2017-12-16 11:02
In theory we should only be sending zid to hubzilla sites. We may have broken this rule in some places during the huge body of work on protocol federation. Apologies but I have not been able to follow where and how this link is getting created. If you can point out how to reproduce I'll see if there is something I can do about it.

**Comment by git-marijus** [comment] 2017-12-16 11:27
Every link in link to source (item dropdown menu) is beeing zidifyed atm...

**Comment by hfroese** [comment] 2017-12-16 12:40
@git-marijus According to the image on top of this thread, the avatar and sentence refers to the sharing user including a link to the original post. "**teilte**" (shared) is the correct expression.

**Comment by git-marijus** [comment] 2017-12-17 10:20
Wrong link and missing content should be fixed now. What is left to fix is the missing xchan for @hfroese. This actually worked for me in all test cases.

**Comment by git-marijus** [comment] 2017-12-17 21:30
Fixed.

**Closed by git-marijus** 2017-12-17 21:30 UTC
